export const CROP_SELECT_OPTIONS: { label: string; value: string | number }[] =
  [
    { value: "Wheat", label: "밀" },
    { value: "Rice", label: "쌀" },
    { value: "Corn", label: "옥수수" },
    { value: "Sugarcane", label: "사탕수수" },
    { value: "Potatoes", label: "감자" },
    { value: "Tomatoes", label: "토마토" },
    { value: "Bananas", label: "바나나" },
    { value: "Pistachios", label: "피스타치오" },
    { value: "Dates", label: "대추야자" },
    { value: "Onions", label: "양파" },
    { value: "Grapes", label: "포도" },
    { value: "Almonds", label: "아몬드" },
    { value: "Sesame", label: "참깨" },
    { value: "Olives", label: "올리브" },
    { value: "Apples", label: "사과" },
    { value: "Peppers", label: "피망" },
    { value: "Watermelon", label: "수박" },
    { value: "Melons", label: "멜론" },
    { value: "Oranges", label: "오렌지" },
    { value: "Lemons", label: "레몬" },
    { value: "Avocados", label: "아보카도" },
    { value: "Cabbage", label: "양배추" },
    { value: "Eggplant", label: "가지" },
    { value: "Squash", label: "호박" },
    { value: "Sweet Potatoes", label: "고구마" },
    { value: "Peanuts", label: "땅콩" },
    { value: "Tea Plants", label: "차나무" },
    { value: "Parsley", label: "파슬리" },
    { value: "Pecans", label: "피칸" },
    { value: "Garlic", label: "마늘" },
  ];
